### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by davidortinau** [davidortinau/Xappy#16]
# Description

A page of details about:

- contributors linking to their preferred profiles
- versions
- dependencies

## Sub Tasks

- [ ] Do This
- [ ] Do That

**Comment by DanielCauser** [comment]
Hey @davidortinau,  I would like to grab this puppy.

**Comment by Depechie** [comment]
Hey @davidortinau wonder what you are thinking about this screen?
There used to be an awesome lib called YLAD for Windows Phone, that auto generated Version content based off an XML that was included in the project.
So as a dev, you only needed to enter the same stuff you would enter in the App distribution pages when releasing the app and provide a version number.
The lib would use that XML to present this info to the user in the About page.
( only coding found of the remains : https://github.com/FalafelSoftwareInc/YLAD-Universal )

If this sound something nice to have in Xappy, I would like to take up this issue... of course seeing we are now 2019 I guess a JSON structure would do too.

**Comment by davidortinau** [comment]
Sounds good, it's all yours. We have a design started for this, but I think it needs more thought about content. Additional ideas welcome.

**Comment by Depechie** [comment]
Was thinking of maybe trying to retrieve the contributors of this repo through REST and list those... and doing a grouped listview for each version number with features of each app releas. Based on the xml or json file.

**Comment by Depechie** [comment]
Just tried it... the Octokit nuget from GitHub ( https://github.com/octokit/octokit.net ) has this build in!

`var collaboraters = await client.Repository.GetAllContributors("davidortinau", "Xappy")`

**Comment by Depechie** [comment]
@davidortinau this was not 100% finished. So wondering on your thoughts on what I can do to improve this? Was there a final design already for these pages?

**Comment by davidortinau** [comment]
No design. I can come up with one, or feel free to suggest something. DIdn't mean to close the issue, I just wanted to get the progress merged. Oops.
