### ISSUE TITLE
[Bug] Flyout gradient on iOS improperly sized

### ISSUE THREAD

**Issue by davidortinau** [davidortinau/Xappy#23]
I totally hacked this together with a hardcoded value b/c I've yet to figure out the CALayer mojo to get the expected result. 

https://github.com/davidortinau/Xappy/blob/master/Xappy/Xappy.iOS/Renderers/XappyShellRenderer.cs#L47

fwiw - straight up setting the background color works fine. Gradient is sized for iPhone X. Not:

<img width="524" alt="Screenshot 2019-05-03 at 00 15 01" src="https://user-images.githubusercontent.com/41873/57110855-a6a80400-6cff-11e9-8f0c-9e6cc8a5c7bc.png">

**Comment by anotherlab** [comment]
I just started seeing this on iOS when I updated from XF 4.2 to XF 4.3.   If you compile Xappy with XF 4.3, the flyout view bounds in XappyShellRenderer.OnFlyoutWillAppear are for the full screen.  When the flyout is closed, you see an extra strip of gradient

![poorxappy](https://user-images.githubusercontent.com/1191188/69491087-5391cc00-0e5e-11ea-8c5e-56d33ccd7596.png)

When you invoke the flyout, the gradient view is full screen width.  Where and when is the flyout width being calculated?
